import { Award, BookOpen, Calendar, Coins, Crown, Flame, Footprints, Gem, Scroll, Shield, Sparkles, Star, Target, Trophy, Zap } from 'lucide-react';

export const BOOK_BADGES = [
  // --- KATEGORIE: KNIHY (30) ---
  { id: 'bookworm_1', title: 'První Průzkumník', description: 'Přečti celkem 1 knih.', icon: Footprints, category: 'books', rewardCoins: 50, rewardXp: 100, condition: (s) => (s?.totalRead || 0) >= 1 },
  { id: 'bookworm_2', title: 'Stránkový Učeň', description: 'Přečti celkem 2 knih.', icon: BookOpen, category: 'books', rewardCoins: 60, rewardXp: 120, condition: (s) => (s?.totalRead || 0) >= 2 },
  { id: 'bookworm_3', title: 'Nedočkavý Čtenář', description: 'Přečti celkem 3 knih.', icon: BookOpen, category: 'books', rewardCoins: 75, rewardXp: 150, condition: (s) => (s?.totalRead || 0) >= 3 },
  { id: 'bookworm_4', title: 'Kapitolový Lovec', description: 'Přečti celkem 4 knih.', icon: Scroll, category: 'books', rewardCoins: 90, rewardXp: 180, condition: (s) => (s?.totalRead || 0) >= 4 },
  { id: 'bookworm_5', title: 'Zapálený Čtenář', description: 'Přečti celkem 5 knih.', icon: Trophy, category: 'books', rewardCoins: 120, rewardXp: 250, condition: (s) => (s?.totalRead || 0) >= 5 },
  { id: 'bookworm_7', title: 'Čtenářský Entuziasta', description: 'Přečti celkem 7 knih.', icon: BookOpen, category: 'books', rewardCoins: 150, rewardXp: 300, condition: (s) => (s?.totalRead || 0) >= 7 },
  { id: 'bookworm_10', title: 'Knihovní Štamgast', description: 'Přečti celkem 10 knih.', icon: Scroll, category: 'books', rewardCoins: 200, rewardXp: 400, condition: (s) => (s?.totalRead || 0) >= 10 },
  { id: 'bookworm_12', title: 'Průkopník Příběhů', description: 'Přečti celkem 12 knih.', icon: BookOpen, category: 'books', rewardCoins: 220, rewardXp: 450, condition: (s) => (s?.totalRead || 0) >= 12 },
  { id: 'bookworm_15', title: 'Sběratel Svazků', description: 'Přečti celkem 15 knih.', icon: Award, category: 'books', rewardCoins: 250, rewardXp: 500, condition: (s) => (s?.totalRead || 0) >= 15 },
  { id: 'bookworm_18', title: 'Strážce Znalostí', description: 'Přečti celkem 18 knih.', icon: Shield, category: 'books', rewardCoins: 280, rewardXp: 550, condition: (s) => (s?.totalRead || 0) >= 18 },
  { id: 'bookworm_20', title: 'Knižní Vášnivec', description: 'Přečti celkem 20 knih.', icon: Trophy, category: 'books', rewardCoins: 300, rewardXp: 600, condition: (s) => (s?.totalRead || 0) >= 20 },
  { id: 'bookworm_25', title: 'Knihomil Roku', description: 'Přečti celkem 25 knih.', icon: Award, category: 'books', rewardCoins: 350, rewardXp: 800, condition: (s) => (s?.totalRead || 0) >= 25 },
  { id: 'bookworm_30', title: 'Archivář Příběhů', description: 'Přečti celkem 30 knih.', icon: Scroll, category: 'books', rewardCoins: 400, rewardXp: 900, condition: (s) => (s?.totalRead || 0) >= 30 },
  { id: 'bookworm_35', title: 'Mistr svazků', description: 'Přečti celkem 35 knih.', icon: Award, category: 'books', rewardCoins: 450, rewardXp: 1000, condition: (s) => (s?.totalRead || 0) >= 35 },
  { id: 'bookworm_40', title: 'Knihovní Doyenne', description: 'Přečti celkem 40 knih.', icon: Crown, category: 'books', rewardCoins: 500, rewardXp: 1200, condition: (s) => (s?.totalRead || 0) >= 40 },
  { id: 'bookworm_45', title: 'Vládce Stránek', description: 'Přečti celkem 45 knih.', icon: Shield, category: 'books', rewardCoins: 600, rewardXp: 1400, condition: (s) => (s?.totalRead || 0) >= 45 },
  { id: 'bookworm_50', title: 'Pán Příběhů', description: 'Přečti celkem 50 knih.', icon: Crown, category: 'books', rewardCoins: 800, rewardXp: 2000, condition: (s) => (s?.totalRead || 0) >= 50 },
  { id: 'bookworm_60', title: 'Mystický Čtenář', description: 'Přečti celkem 60 knih.', icon: Sparkles, category: 'books', rewardCoins: 900, rewardXp: 2200, condition: (s) => (s?.totalRead || 0) >= 60 },
  { id: 'bookworm_70', title: 'Dobyvatel Knihovny', description: 'Přečti celkem 70 knih.', icon: Trophy, category: 'books', rewardCoins: 1000, rewardXp: 2500, condition: (s) => (s?.totalRead || 0) >= 70 },
  { id: 'bookworm_80', title: 'Legendární Knihomol', description: 'Přečti celkem 80 knih.', icon: Award, category: 'books', rewardCoins: 1200, rewardXp: 2800, condition: (s) => (s?.totalRead || 0) >= 80 },
  { id: 'bookworm_90', title: 'Velmistr Četby', description: 'Přečti celkem 90 knih.', icon: Crown, category: 'books', rewardCoins: 1400, rewardXp: 3200, condition: (s) => (s?.totalRead || 0) >= 90 },
  { id: 'bookworm_100', title: 'Stoletý Archivář', description: 'Přečti celkem 100 knih.', icon: Gem, category: 'books', rewardCoins: 2000, rewardXp: 5000, condition: (s) => (s?.totalRead || 0) >= 100 },
  { id: 'bookworm_125', title: 'Absolutní Knihomol', description: 'Přečti celkem 125 knih.', icon: Gem, category: 'books', rewardCoins: 2300, rewardXp: 5500, condition: (s) => (s?.totalRead || 0) >= 125 },
  { id: 'bookworm_150', title: 'Bůh Litery', description: 'Přečti celkem 150 knih.', icon: Crown, category: 'books', rewardCoins: 2600, rewardXp: 6000, condition: (s) => (s?.totalRead || 0) >= 150 },
  { id: 'bookworm_175', title: 'Císař Svazků', description: 'Přečti celkem 175 knih.', icon: Crown, category: 'books', rewardCoins: 3000, rewardXp: 7000, condition: (s) => (s?.totalRead || 0) >= 175 },
  { id: 'bookworm_200', title: 'Nezničitelný Čtenář', description: 'Přečti celkem 200 knih.', icon: Shield, category: 'books', rewardCoins: 3500, rewardXp: 8000, condition: (s) => (s?.totalRead || 0) >= 200 },
  { id: 'bookworm_250', title: 'Věčný Čtenář', description: 'Přečti celkem 250 knih.', icon: Sparkles, category: 'books', rewardCoins: 4000, rewardXp: 9000, condition: (s) => (s?.totalRead || 0) >= 250 },
  { id: 'bookworm_300', title: 'Kosmický Čtenář', description: 'Přečti celkem 300 knih.', icon: Star, category: 'books', rewardCoins: 5000, rewardXp: 10000, condition: (s) => (s?.totalRead || 0) >= 300 },
  { id: 'bookworm_400', title: 'Nekonečný Archivář', description: 'Přečti celkem 400 knih.', icon: Zap, category: 'books', rewardCoins: 7500, rewardXp: 15000, condition: (s) => (s?.totalRead || 0) >= 400 },
  { id: 'bookworm_500', title: 'Živoucí Knihovna', description: 'Přečti celkem 500 knih.', icon: Gem, category: 'books', rewardCoins: 10000, rewardXp: 20000, condition: (s) => (s?.totalRead || 0) >= 500 },

  // --- KATEGORIE: STREAK (25) ---
  { id: 'streak_1', title: 'Jiskra Touhy', description: 'Čti 1 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 20, rewardXp: 30, condition: (s) => (s?.streak || 0) >= 1 },
  { id: 'streak_2', title: 'Dvoudenní Plamínek', description: 'Čti 2 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 30, rewardXp: 45, condition: (s) => (s?.streak || 0) >= 2 },
  { id: 'streak_3', title: 'Malá Jiskra', description: 'Čti 3 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 40, rewardXp: 60, condition: (s) => (s?.streak || 0) >= 3 },
  { id: 'streak_4', title: 'Rozhořívající se Plameň', description: 'Čti 4 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 50, rewardXp: 80, condition: (s) => (s?.streak || 0) >= 4 },
  { id: 'streak_5', title: 'Pětidenní Žár', description: 'Čti 5 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 70, rewardXp: 100, condition: (s) => (s?.streak || 0) >= 5 },
  { id: 'streak_6', title: 'Šestidenní Vytrvalost', description: 'Čti 6 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 90, rewardXp: 130, condition: (s) => (s?.streak || 0) >= 6 },
  { id: 'streak_7', title: 'Týdenní Plamen', description: 'Čti 7 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 150, rewardXp: 300, condition: (s) => (s?.streak || 0) >= 7 },
  { id: 'streak_10', title: 'Desetidenní Záře', description: 'Čti 10 dní v kuse bez přerušení.', icon: Zap, category: 'streak', rewardCoins: 200, rewardXp: 400, condition: (s) => (s?.streak || 0) >= 10 },
  { id: 'streak_14', title: 'Hořící Odhodlání', description: 'Čti 14 dní v kuse bez přerušení.', icon: Zap, category: 'streak', rewardCoins: 300, rewardXp: 600, condition: (s) => (s?.streak || 0) >= 14 },
  { id: 'streak_21', title: 'Třítýdenní Rituál', description: 'Čti 21 dní v kuse bez přerušení.', icon: Sparkles, category: 'streak', rewardCoins: 450, rewardXp: 900, condition: (s) => (s?.streak || 0) >= 21 },
  { id: 'streak_30', title: 'Měsíční Mág', description: 'Čti 30 dní v kuse bez přerušení.', icon: Sparkles, category: 'streak', rewardCoins: 600, rewardXp: 1500, condition: (s) => (s?.streak || 0) >= 30 },
  { id: 'streak_40', title: 'Nezlomný Čtenář', description: 'Čti 40 dní v kuse bez přerušení.', icon: Shield, category: 'streak', rewardCoins: 800, rewardXp: 1800, condition: (s) => (s?.streak || 0) >= 40 },
  { id: 'streak_50', title: 'Padesátidenní Oheň', description: 'Čti 50 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 1000, rewardXp: 2200, condition: (s) => (s?.streak || 0) >= 50 },
  { id: 'streak_60', title: 'Nezastavitelný Žár', description: 'Čti 60 dní v kuse bez přerušení.', icon: Gem, category: 'streak', rewardCoins: 1200, rewardXp: 3000, condition: (s) => (s?.streak || 0) >= 60 },
  { id: 'streak_75', title: 'Plamenná Sféra', description: 'Čti 75 dní v kuse bez přerušení.', icon: Sparkles, category: 'streak', rewardCoins: 1500, rewardXp: 3500, condition: (s) => (s?.streak || 0) >= 75 },
  { id: 'streak_90', title: 'Čtvrtletní Legenda', description: 'Čti 90 dní v kuse bez přerušení.', icon: Trophy, category: 'streak', rewardCoins: 1800, rewardXp: 4000, condition: (s) => (s?.streak || 0) >= 90 },
  { id: 'streak_100', title: 'Sto Dní Oznámení', description: 'Čti 100 dní v kuse bez přerušení.', icon: Crown, category: 'streak', rewardCoins: 2500, rewardXp: 5000, condition: (s) => (s?.streak || 0) >= 100 },
  { id: 'streak_120', title: 'Knižní Fénix', description: 'Čti 120 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 3000, rewardXp: 6000, condition: (s) => (s?.streak || 0) >= 120 },
  { id: 'streak_150', title: 'Nezničitelný Plamen', description: 'Čti 150 dní v kuse bez přerušení.', icon: Shield, category: 'streak', rewardCoins: 3500, rewardXp: 7000, condition: (s) => (s?.streak || 0) >= 150 },
  { id: 'streak_180', title: 'Půlroční Šampion', description: 'Čti 180 dní v kuse bez přerušení.', icon: Award, category: 'streak', rewardCoins: 4000, rewardXp: 8000, condition: (s) => (s?.streak || 0) >= 180 },
  { id: 'streak_200', title: 'Magický Oheň', description: 'Čti 200 dní v kuse bez přerušení.', icon: Sparkles, category: 'streak', rewardCoins: 4500, rewardXp: 9000, condition: (s) => (s?.streak || 0) >= 200 },
  { id: 'streak_250', title: 'Čtenářská Supernova', description: 'Čti 250 dní v kuse bez přerušení.', icon: Star, category: 'streak', rewardCoins: 5500, rewardXp: 11000, condition: (s) => (s?.streak || 0) >= 250 },
  { id: 'streak_300', title: 'Věčný Plamen', description: 'Čti 300 dní v kuse bez přerušení.', icon: Flame, category: 'streak', rewardCoins: 7000, rewardXp: 14000, condition: (s) => (s?.streak || 0) >= 300 },
  { id: 'streak_365', title: 'Roční Čtenářský Bůh', description: 'Čti 365 dní v kuse bez přerušení.', icon: Crown, category: 'streak', rewardCoins: 10000, rewardXp: 25000, condition: (s) => (s?.streak || 0) >= 365 },
  { id: 'streak_500', title: 'Kosmický Oheň Znalostí', description: 'Čti 500 dní v kuse bez přerušení.', icon: Gem, category: 'streak', rewardCoins: 15000, rewardXp: 35000, condition: (s) => (s?.streak || 0) >= 500 },

  // --- KATEGORIE: ÚROVNĚ (25) ---
  { id: 'level_2', title: 'Nováček Archivu', description: 'Dosáhni úrovně 2.', icon: Footprints, category: 'levels', rewardCoins: 30, rewardXp: 50, condition: (s) => (s?.level || 0) >= 2 },
  { id: 'level_3', title: 'Učeň Slova', description: 'Dosáhni úrovně 3.', icon: BookOpen, category: 'levels', rewardCoins: 50, rewardXp: 80, condition: (s) => (s?.level || 0) >= 3 },
  { id: 'level_4', title: 'Průzkumník Svazků', description: 'Dosáhni úrovně 4.', icon: Scroll, category: 'levels', rewardCoins: 80, rewardXp: 120, condition: (s) => (s?.level || 0) >= 4 },
  { id: 'level_5', title: 'Pokročilý Adept', description: 'Dosáhni úrovně 5.', icon: Shield, category: 'levels', rewardCoins: 150, rewardXp: 200, condition: (s) => (s?.level || 0) >= 5 },
  { id: 'level_6', title: 'Odhodlaný Čtenář', description: 'Dosáhni úrovně 6.', icon: Trophy, category: 'levels', rewardCoins: 200, rewardXp: 250, condition: (s) => (s?.level || 0) >= 6 },
  { id: 'level_7', title: 'Adept Tajemství', description: 'Dosáhni úrovně 7.', icon: Sparkles, category: 'levels', rewardCoins: 250, rewardXp: 300, condition: (s) => (s?.level || 0) >= 7 },
  { id: 'level_8', title: 'Čtenářský Znalec', description: 'Dosáhni úrovně 8.', icon: Award, category: 'levels', rewardCoins: 300, rewardXp: 350, condition: (s) => (s?.level || 0) >= 8 },
  { id: 'level_9', title: 'Strážce Textu', description: 'Dosáhni úrovně 9.', icon: Shield, category: 'levels', rewardCoins: 350, rewardXp: 400, condition: (s) => (s?.level || 0) >= 9 },
  { id: 'level_10', title: 'Mistr Sečtělosti', description: 'Dosáhni úrovně 10.', icon: Star, category: 'levels', rewardCoins: 400, rewardXp: 500, condition: (s) => (s?.level || 0) >= 10 },
  { id: 'level_12', title: 'Strážce Znaného', description: 'Dosáhni úrovně 12.', icon: Scroll, category: 'levels', rewardCoins: 500, rewardXp: 600, condition: (s) => (s?.level || 0) >= 12 },
  { id: 'level_14', title: 'Elitní Čtenář', description: 'Dosáhni úrovně 14.', icon: Trophy, category: 'levels', rewardCoins: 600, rewardXp: 700, condition: (s) => (s?.level || 0) >= 14 },
  { id: 'level_15', title: 'Mág Nejvyšší Knihovny', description: 'Dosáhni úrovně 15.', icon: Zap, category: 'levels', rewardCoins: 800, rewardXp: 1000, condition: (s) => (s?.level || 0) >= 15 },
  { id: 'level_18', title: 'Geniální Archivář', description: 'Dosáhni úrovně 18.', icon: Sparkles, category: 'levels', rewardCoins: 1000, rewardXp: 1200, condition: (s) => (s?.level || 0) >= 18 },
  { id: 'level_20', title: 'Legenda Archivu', description: 'Dosáhni úrovně 20.', icon: Crown, category: 'levels', rewardCoins: 1200, rewardXp: 1500, condition: (s) => (s?.level || 0) >= 20 },
  { id: 'level_25', title: 'Vševědoucí Čtenář', description: 'Dosáhni úrovně 25.', icon: Crown, category: 'levels', rewardCoins: 1600, rewardXp: 2000, condition: (s) => (s?.level || 0) >= 25 },
  { id: 'level_30', title: 'Mystický Šampion', description: 'Dosáhni úrovně 30.', icon: Gem, category: 'levels', rewardCoins: 2000, rewardXp: 2500, condition: (s) => (s?.level || 0) >= 30 },
  { id: 'level_35', title: 'Transcendentní Čtenář', description: 'Dosáhni úrovně 35.', icon: Sparkles, category: 'levels', rewardCoins: 2500, rewardXp: 3000, condition: (s) => (s?.level || 0) >= 35 },
  { id: 'level_40', title: 'Vládce Písmen', description: 'Dosáhni úrovně 40.', icon: Shield, category: 'levels', rewardCoins: 3000, rewardXp: 4000, condition: (s) => (s?.level || 0) >= 40 },
  { id: 'level_45', title: 'Věčný Učenec', description: 'Dosáhni úrovně 45.', icon: BookOpen, category: 'levels', rewardCoins: 3500, rewardXp: 4500, condition: (s) => (s?.level || 0) >= 45 },
  { id: 'level_50', title: 'Polobůh Knihovny', description: 'Dosáhni úrovně 50.', icon: Crown, category: 'levels', rewardCoins: 5000, rewardXp: 6000, condition: (s) => (s?.level || 0) >= 50 },
  { id: 'level_60', title: 'Archivář Všehomíra', description: 'Dosáhni úrovně 60.', icon: Gem, category: 'levels', rewardCoins: 6500, rewardXp: 8000, condition: (s) => (s?.level || 0) >= 60 },
  { id: 'level_70', title: 'Absolutní Mistr', description: 'Dosáhni úrovně 70.', icon: Star, category: 'levels', rewardCoins: 8000, rewardXp: 10000, condition: (s) => (s?.level || 0) >= 70 },
  { id: 'level_80', title: 'Strážce Věčnosti', description: 'Dosáhni úrovně 80.', icon: Shield, category: 'levels', rewardCoins: 10000, rewardXp: 12000, condition: (s) => (s?.level || 0) >= 80 },
  { id: 'level_90', title: 'Kosmický Šampion', description: 'Dosáhni úrovně 90.', icon: Zap, category: 'levels', rewardCoins: 12500, rewardXp: 15000, condition: (s) => (s?.level || 0) >= 90 },
  { id: 'level_100', title: 'Bůh Zapomenutých Příběhů', description: 'Dosáhni úrovně 100.', icon: Crown, category: 'levels', rewardCoins: 20000, rewardXp: 25000, condition: (s) => (s?.level || 0) >= 100 },

  // --- KATEGORIE: VÝZVY (10) ---
  { id: 'goal_1', title: 'První Měsíční Cíl', description: 'Splň měsíční čtenářský cíl.', icon: Target, category: 'monthly', rewardCoins: 250, rewardXp: 500, condition: (s) => (s?.monthlyRead || 0) >= (s?.monthlyGoal || 25) && (s?.monthlyGoal || 0) > 0 },
  { id: 'monthly_1', title: 'Jednička Měsíce', description: 'Přečti alespoň 1 knihu v aktuálním měsíci.', icon: BookOpen, category: 'monthly', rewardCoins: 50, rewardXp: 100, condition: (s) => (s?.monthlyRead || 0) >= 1 },
  { id: 'monthly_2', title: 'Dva Svazky Měsíce', description: 'Přečti alespoň 2 knihy v aktuálním měsíci.', icon: BookOpen, category: 'monthly', rewardCoins: 80, rewardXp: 150, condition: (s) => (s?.monthlyRead || 0) >= 2 },
  { id: 'monthly_5', title: 'Pět v Měsíci', description: 'Přečti alespoň 5 knih během jednoho měsíce.', icon: Calendar, category: 'monthly', rewardCoins: 150, rewardXp: 300, condition: (s) => (s?.monthlyRead || 0) >= 5 },
  { id: 'monthly_7', title: 'Týdenní Dávka Měsíce', description: 'Přečti alespoň 7 knih v aktuálním měsíci.', icon: Award, category: 'monthly', rewardCoins: 200, rewardXp: 400, condition: (s) => (s?.monthlyRead || 0) >= 7 },
  { id: 'monthly_10', title: 'Měsíční Smršť', description: 'Přečti alespoň 10 knih během jednoho měsíce.', icon: Zap, category: 'monthly', rewardCoins: 300, rewardXp: 600, condition: (s) => (s?.monthlyRead || 0) >= 10 },
  { id: 'monthly_15', title: 'Extrémní Měsíc', description: 'Přečti alespoň 15 knih během jednoho měsíce.', icon: Trophy, category: 'monthly', rewardCoins: 500, rewardXp: 1000, condition: (s) => (s?.monthlyRead || 0) >= 15 },
  { id: 'monthly_20', title: 'Knižní Maraton', description: 'Přečti alespoň 20 knih během jednoho měsíce.', icon: Crown, category: 'monthly', rewardCoins: 800, rewardXp: 1500, condition: (s) => (s?.monthlyRead || 0) >= 20 },
  { id: 'goal_high', 'title': 'Ambitiózní Cíl', description: 'Měj měsíční cíl nastaven na 30+ knih a splň ho.', icon: Target, category: 'monthly', rewardCoins: 600, rewardXp: 1200, condition: (s) => (s?.monthlyRead || 0) >= (s?.monthlyGoal || 0) && (s?.monthlyGoal || 0) >= 30 },
  { id: 'goal_master', 'title': 'Super Cíl', description: 'Měj měsíční cíl nastaven na 50+ knih a splň ho.', icon: Crown, category: 'monthly', rewardCoins: 1500, rewardXp: 3000, condition: (s) => (s?.monthlyRead || 0) >= (s?.monthlyGoal || 0) && (s?.monthlyGoal || 0) >= 50 },

  // --- KATEGORIE: SPECIÁLNÍ (10) ---
  { id: 'coins_100', title: 'Spořivý Čtenář', description: 'Nasmírej celkem 100 Jomarid Coinů.', icon: Coins, category: 'special', rewardCoins: 50, rewardXp: 100, condition: (s) => (s?.jomaridCoins || 0) >= 100 },
  { id: 'coins_500', title: 'Mincový Sběratel', description: 'Nasmírej celkem 500 Jomarid Coinů.', icon: Coins, category: 'special', rewardCoins: 150, rewardXp: 300, condition: (s) => (s?.jomaridCoins || 0) >= 500 },
  { id: 'coins_1000', title: 'Boháč Knihovny', description: 'Nasmírej celkem 1,000 Jomarid Coinů.', icon: Coins, category: 'special', rewardCoins: 300, rewardXp: 600, condition: (s) => (s?.jomaridCoins || 0) >= 1000 },
  { id: 'coins_5000', title: 'Zlatý Archivář', description: 'Nasmírej celkem 5,000 Jomarid Coinů.', icon: Gem, category: 'special', rewardCoins: 1000, rewardXp: 2000, condition: (s) => (s?.jomaridCoins || 0) >= 5000 },
  { id: 'badge_collector_5', title: 'Začínající Sběratel', description: 'Odemkni alespoň 5 odznaků.', icon: Award, category: 'special', rewardCoins: 100, rewardXp: 200, condition: (s) => (s?.unlockedBadges?.length || 0) >= 5 },
  { id: 'badge_collector_10', title: 'Vášnivý Sběratel', description: 'Odemkni alespoň 10 odznaků.', icon: Award, category: 'special', rewardCoins: 200, rewardXp: 400, condition: (s) => (s?.unlockedBadges?.length || 0) >= 10 },
  { id: 'badge_collector_25', title: 'Mistr Odznaků', description: 'Odemkni alespoň 25 odznaků.', icon: Trophy, category: 'special', rewardCoins: 500, rewardXp: 1000, condition: (s) => (s?.unlockedBadges?.length || 0) >= 25 },
  { id: 'badge_collector_50', title: 'Legendární Sběratel', description: 'Odemkni alespoň 50 odznaků.', icon: Crown, category: 'special', rewardCoins: 1500, rewardXp: 3000, condition: (s) => (s?.unlockedBadges?.length || 0) >= 50 },
  { id: 'badge_collector_75', title: 'Elitní Sběratel', description: 'Odemkni alespoň 75 odznaků.', icon: Gem, category: 'special', rewardCoins: 3000, rewardXp: 6000, condition: (s) => (s?.unlockedBadges?.length || 0) >= 75 },
  { id: 'badge_collector_100', title: 'Absolutní Sběratel 100+', description: 'Odemkni 100 a více odznaků!', icon: Crown, category: 'special', rewardCoins: 10000, rewardXp: 20000, condition: (s) => (s?.unlockedBadges?.length || 0) >= 100 }
];
